parameters:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build project - ${{parameters.buildConfiguration}}'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration ${{parameters.buildConfiguration}}'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish project - ${{parameters.buildConfiguration}}'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration ${{parameters.buildConfiguration}} --output ${{parameters.buildConfiguration}}'
    zipAfterPublish: true
